//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubscriberBase.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Connection
    {
        public System.Guid ConnectionID { get; set; }
        public System.DateTime ConnectionDate { get; set; }
        public string PhoneNumb { get; set; }
        public System.Guid OperatorID { get; set; }
        public System.Guid TariffID { get; set; }
        public System.Guid SubscriberID { get; set; }
    
        public virtual Operators Operators { get; set; }
        public virtual Subscribers Subscribers { get; set; }
        public virtual Tariffs Tariffs { get; set; }
    }
}
